import { createClient } from '@supabase/supabase-js';
import './styles.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;

const menuItems = [
  { name: 'Truffle Tagliolini', category: 'dinner', description: 'Hand-cut pasta, black truffle, parmesan cream', price: '$26', rating: '4.9', image: 'https://images.pexels.com/photos/36921419/pexels-photo-36921419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Citrus Burrata', category: 'lunch', description: 'Whipped burrata, blood orange, pistachio, basil oil', price: '$18', rating: '4.8', image: 'https://images.pexels.com/photos/5865275/pexels-photo-5865275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Miso Glazed Salmon', category: 'dinner', description: 'Wild salmon, charred leek, ginger dashi', price: '$32', rating: '4.9', image: 'https://images.pexels.com/photos/33097101/pexels-photo-33097101.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Morning Shakshuka', category: 'breakfast', description: 'Baked eggs, spiced tomato, feta, toasted sourdough', price: '$16', rating: '4.7', image: 'https://images.pexels.com/photos/9571434/pexels-photo-9571434.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Black Ravioli', category: 'dinner', description: 'Lobster, brown butter, heirloom tomato, chive', price: '$29', rating: '5.0', image: 'https://images.pexels.com/photos/4871266/pexels-photo-4871266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Berry Pavlova', category: 'desserts', description: 'Crisp meringue, vanilla cream, seasonal berries', price: '$12', rating: '4.8', image: 'https://images.pexels.com/photos/6223229/pexels-photo-6223229.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
];

const galleryImages = [
  'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/36430088/pexels-photo-36430088.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/36921419/pexels-photo-36921419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/33097101/pexels-photo-33097101.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/5865275/pexels-photo-5865275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/5041488/pexels-photo-5041488.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
];

const app = document.querySelector('#app');
app.innerHTML = `
  <div class="site-shell">
    <header class="site-header" id="top">
      <a class="brand" href="#home" aria-label="Savoré home"><span class="brand-mark">S</span><span>SAVORÉ</span></a>
      <button class="menu-toggle" aria-label="Open menu" aria-expanded="false"><span></span><span></span></button>
      <nav class="site-nav" aria-label="Main navigation">
        <a href="#home">Home</a><a href="#about">About</a><a href="#menu">Menu</a><a href="#services">Services</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a>
        <button class="button button-small js-reserve">Book a table <span>↗</span></button>
      </nav>
      <button class="theme-toggle" aria-label="Toggle light and dark mode"><span>◐</span></button>
    </header>

    <main>
      <section class="hero section-dark" id="home">
        <div class="hero-image"></div><div class="hero-overlay"></div>
        <div class="hero-content reveal"><p class="eyebrow">A table worth gathering around</p><h1>Modern dining.<br><em>Made memorable.</em></h1><p class="hero-copy">Seasonal ingredients, open-fire cooking, and the kind of hospitality that makes an ordinary evening feel like an occasion.</p><div class="hero-actions"><a class="button" href="#menu">Explore our menu <span>↗</span></a><button class="text-button js-reserve">Book a table <span>↗</span></button></div></div>
        <div class="hero-meta"><span>SCROLL TO EXPLORE</span><span class="scroll-line"></span><span>EST. 2014 · NEW YORK</span></div>
      </section>

      <section class="intro section-light" id="about"><div class="section-kicker reveal"><span>01</span><span class="kicker-line"></span><span>OUR STORY</span></div><div class="intro-grid"><div class="intro-title reveal"><h2>We cook with <em>intention.</em></h2><a class="underlined-link" href="#contact">Discover more <span>↗</span></a></div><div class="intro-copy reveal"><p class="large-copy">Savoré is a neighborhood restaurant with a restless curiosity. Our menu follows the seasons, our room follows the light, and our table is always set for one more.</p><p>Led by Chef Camille Laurent, our kitchen brings a quietly bold point of view to familiar ingredients. Nothing fussy. Nothing forgotten. Just honest food, carefully made.</p></div></div><div class="stats reveal"><div><strong>10<span>+</span></strong><small>Years of<br>experience</small></div><div><strong>50<span>+</span></strong><small>Thoughtful<br>dishes</small></div><div><strong>20<span>+</span></strong><small>Passionate<br>chefs</small></div><div><strong>10k<span>+</span></strong><small>Happy<br>guests</small></div></div></section>

      <section class="menu-section section-cream" id="menu"><div class="section-heading reveal"><div class="section-kicker"><span>02</span><span class="kicker-line"></span><span>FROM THE KITCHEN</span></div><h2>A little something<br><em>for everyone.</em></h2><p>Our menu changes with the seasons. These are a few current favorites.</p></div><div class="filters" role="tablist"><button class="filter active" data-filter="all">All</button><button class="filter" data-filter="breakfast">Breakfast</button><button class="filter" data-filter="lunch">Lunch</button><button class="filter" data-filter="dinner">Dinner</button><button class="filter" data-filter="desserts">Desserts</button></div><div class="menu-grid" id="menu-grid"></div></section>

      <section class="offer section-dark"><div class="offer-image"></div><div class="offer-content reveal"><p class="eyebrow">For the weekend</p><h2>Good food.<br><em>Better company.</em></h2><p>Join us every Friday and Saturday for an evening of shared plates, generous pours, and a little extra magic.</p><div class="offer-badge"><strong>20% OFF</strong><span>on your second bottle<br>of wine</span></div><button class="button js-reserve">Reserve your table <span>↗</span></button><div class="countdown"><span>THIS OFFER ENDS IN</span><div><strong id="days">02</strong><small>DAYS</small></div><i>:</i><div><strong id="hours">14</strong><small>HRS</small></div><i>:</i><div><strong id="minutes">36</strong><small>MIN</small></div><i>:</i><div><strong id="seconds">52</strong><small>SEC</small></div></div></div></section>

      <section class="services section-light" id="services"><div class="section-heading reveal"><div class="section-kicker"><span>03</span><span class="kicker-line"></span><span>WHAT WE DO</span></div><h2>More than<br><em>a meal.</em></h2></div><div class="service-grid"><article class="service-card reveal"><span class="service-number">01</span><span class="service-icon">◒</span><h3>Dine in</h3><p>A warm, considered space for long lunches, late dinners, and everything in between.</p><a class="underlined-link" href="#contact">Join us <span>↗</span></a></article><article class="service-card reveal"><span class="service-number">02</span><span class="service-icon">↗</span><h3>Online ordering</h3><p>Bring a little Savoré home. Our favorites, packed with care and ready when you are.</p><a class="underlined-link" href="#contact">Order now <span>↗</span></a></article><article class="service-card reveal"><span class="service-number">03</span><span class="service-icon">⌂</span><h3>Private events</h3><p>From intimate dinners to big celebrations, we'll make it feel like yours.</p><a class="underlined-link" href="#contact">Plan a party <span>↗</span></a></article></div></section>

      <section class="gallery-section section-cream" id="gallery"><div class="section-heading gallery-heading reveal"><div class="section-kicker"><span>04</span><span class="kicker-line"></span><span>THE SAVORÉ WORLD</span></div><h2>Come for the food.<br><em>Stay for the feeling.</em></h2></div><div class="gallery-grid">${galleryImages.map((image, index) => `<button class="gallery-item gallery-${index + 1} reveal" data-image="${image}" aria-label="View gallery image ${index + 1}"><img src="${image}" alt="Savoré dining moment ${index + 1}"></button>`).join('')}</div></section>

      <section class="reviews section-dark"><div class="review-deco">“</div><div class="section-kicker"><span>05</span><span class="kicker-line"></span><span>GUESTBOOK</span></div><div class="review-slider"><div class="review-copy"><p class="stars">★★★★★</p><blockquote id="review-text">“The kind of place you want to keep to yourself — but love too much not to share.”</blockquote><p class="review-author" id="review-author">— Maya R. · Local Guide</p></div><div class="review-controls"><button id="review-prev" aria-label="Previous review">←</button><span id="review-count">01 / 03</span><button id="review-next" aria-label="Next review">→</button></div></div></section>

      <section class="reservation-cta section-light"><div class="cta-inner reveal"><p class="eyebrow">Your table is waiting</p><h2>Make tonight<br><em>memorable.</em></h2><p>Good things happen around a table. Come pull up a chair.</p><button class="button button-dark js-reserve">Reserve your table <span>↗</span></button></div></section>

      <section class="contact section-cream" id="contact"><div class="contact-info reveal"><div class="section-kicker"><span>06</span><span class="kicker-line"></span><span>FIND US</span></div><h2>Come say<br><em>hello.</em></h2><div class="contact-details"><p><span>ADDRESS</span>214 Mercer Street<br>New York, NY 10012</p><p><span>CONTACT</span><a href="tel:+12125550147">+1 212 555 0147</a><br><a href="mailto:hello@savore.example">hello@savore.example</a></p><p><span>HOURS</span>Mon–Thu · 11:30am–10pm<br>Fri–Sat · 11:30am–11pm<br>Sun · 10am–9pm</p></div></div><form class="contact-form reveal" id="contact-form"><p class="eyebrow">Have a question?</p><h3>Say hello.</h3><label>Your name<input name="full_name" required placeholder="Jane Smith"></label><label>Email address<input type="email" name="email" required placeholder="jane@example.com"></label><label>Subject<input name="subject" required placeholder="What's on your mind?"></label><label>Message<textarea name="message" required rows="4" placeholder="Tell us a little more..."></textarea></label><button class="button button-dark" type="submit">Send message <span>↗</span></button><p class="form-message" id="contact-message" role="status"></p></form></section>
    </main>

    <footer class="site-footer"><div class="footer-top"><a class="brand" href="#home"><span class="brand-mark">S</span><span>SAVORÉ</span></a><p>Thoughtful food.<br>Good people.<br>Always a seat.</p><div class="footer-links"><a href="#menu">Menu</a><a href="#about">Our story</a><a href="#contact">Contact</a><a href="#home">Instagram ↗</a></div><div class="footer-note">© 2024 Savoré Restaurant<br>All rights reserved.</div></div><div class="footer-bottom"><span>NEW YORK, NY</span><span>MADE WITH INTENTION</span><button id="back-top">Back to top ↑</button></div></footer>
  </div>
  <div class="modal" id="reservation-modal" aria-hidden="true"><div class="modal-backdrop"></div><div class="modal-panel" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close" aria-label="Close reservation form">×</button><div class="section-kicker"><span>RESERVATIONS</span><span class="kicker-line"></span><span>SAVORÉ</span></div><h2 id="modal-title">Save your <em>seat.</em></h2><p>We look forward to welcoming you.</p><form id="reservation-form"><div class="form-row"><label>Full name<input name="full_name" required placeholder="Jane Smith"></label><label>Email<input name="email" type="email" required placeholder="jane@example.com"></label></div><div class="form-row"><label>Phone<input name="phone" type="tel" required placeholder="+1 212 555 0147"></label><label>Guests<select name="guests" required><option value="">Select</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option></select></label></div><div class="form-row"><label>Date<input name="reservation_date" type="date" required></label><label>Time<select name="reservation_time" required><option value="">Select a time</option><option>5:30 PM</option><option>6:00 PM</option><option>6:30 PM</option><option>7:00 PM</option><option>7:30 PM</option><option>8:00 PM</option><option>8:30 PM</option></select></label></div><label>Special request <span class="optional">(optional)</span><textarea name="special_request" rows="3" placeholder="Dietary notes, celebrations, seating preferences..."></textarea></label><button class="button button-dark" type="submit">Request reservation <span>↗</span></button><p class="form-message" id="reservation-message" role="status"></p></form></div></div>
  <div class="lightbox" id="lightbox" aria-hidden="true"><button class="lightbox-close" aria-label="Close image">×</button><button class="lightbox-prev" aria-label="Previous image">←</button><img src="" alt="Expanded gallery view"><button class="lightbox-next" aria-label="Next image">→</button></div>
`;

const renderMenu = (filter = 'all') => { document.querySelector('#menu-grid').innerHTML = menuItems.filter((item) => filter === 'all' || item.category === filter).map((item) => `<article class="menu-card reveal"><div class="menu-image"><img src="${item.image}" alt="${item.name}"><span class="rating">★ ${item.rating}</span></div><div class="menu-card-body"><div><h3>${item.name}</h3><p>${item.description}</p></div><strong>${item.price}</strong></div></article>`).join(''); };
renderMenu();

document.querySelectorAll('.filter').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.filter').forEach((item) => item.classList.remove('active')); button.classList.add('active'); renderMenu(button.dataset.filter); observeReveals(); }));

document.querySelector('.menu-toggle').addEventListener('click', () => { const nav = document.querySelector('.site-nav'); const open = nav.classList.toggle('open'); document.querySelector('.menu-toggle').setAttribute('aria-expanded', String(open)); });
document.querySelectorAll('.site-nav a').forEach((link) => link.addEventListener('click', () => document.querySelector('.site-nav').classList.remove('open')));
document.querySelector('.theme-toggle').addEventListener('click', () => document.body.classList.toggle('dark-mode'));
document.querySelector('#back-top').addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));

const modal = document.querySelector('#reservation-modal');
const setModal = (open) => { modal.classList.toggle('open', open); modal.setAttribute('aria-hidden', String(!open)); document.body.classList.toggle('modal-open', open); if (open) modal.querySelector('input').focus(); };
document.querySelectorAll('.js-reserve').forEach((button) => button.addEventListener('click', () => setModal(true)));
document.querySelector('.modal-close').addEventListener('click', () => setModal(false));
document.querySelector('.modal-backdrop').addEventListener('click', () => setModal(false));

document.querySelector('#reservation-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const message = document.querySelector('#reservation-message'); const data = Object.fromEntries(new FormData(form)); data.guests = Number(data.guests); message.textContent = 'Sending your request...'; try { if (supabase) { const { error } = await supabase.from('restaurant_reservations').insert(data); if (error) throw error; } message.textContent = 'Thank you — your reservation request is on its way. We will be in touch shortly.'; form.reset(); } catch { message.textContent = 'We could not send that just now. Please call us at +1 212 555 0147.'; } });

document.querySelector('#contact-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const message = document.querySelector('#contact-message'); const data = Object.fromEntries(new FormData(form)); message.textContent = 'Sending your note...'; try { if (supabase) { const { error } = await supabase.from('restaurant_messages').insert(data); if (error) throw error; } message.textContent = 'Thanks for reaching out. We will be in touch soon.'; form.reset(); } catch { message.textContent = 'We could not send that just now. Please email hello@savore.example.'; } });

let countdownEnd = Date.now() + (2 * 86400000) + (14 * 3600000) + (36 * 60000) + 52000;
const updateCountdown = () => { const remaining = Math.max(0, countdownEnd - Date.now()); const values = [Math.floor(remaining / 86400000), Math.floor((remaining / 3600000) % 24), Math.floor((remaining / 60000) % 60), Math.floor((remaining / 1000) % 60)]; ['days','hours','minutes','seconds'].forEach((id, index) => { document.querySelector(`#${id}`).textContent = String(values[index]).padStart(2, '0'); }); }; updateCountdown(); setInterval(updateCountdown, 1000);

const reviews = [{ text: '“The kind of place you want to keep to yourself — but love too much not to share.”', author: '— Maya R. · Local Guide' }, { text: '“Every detail feels considered, from the first welcome to the last perfect bite.”', author: '— Daniel K. · Dinner guest' }, { text: '“Savoré has become our favorite kind of ritual. Warm, quietly beautiful, and delicious.”', author: '— Priya S. · Regular' }]; let reviewIndex = 0; const setReview = (direction) => { reviewIndex = (reviewIndex + direction + reviews.length) % reviews.length; document.querySelector('#review-text').textContent = reviews[reviewIndex].text; document.querySelector('#review-author').textContent = reviews[reviewIndex].author; document.querySelector('#review-count').textContent = `0${reviewIndex + 1} / 03`; }; document.querySelector('#review-prev').addEventListener('click', () => setReview(-1)); document.querySelector('#review-next').addEventListener('click', () => setReview(1));

const lightbox = document.querySelector('#lightbox'); const lightboxImage = lightbox.querySelector('img'); let galleryIndex = 0; const openLightbox = (index) => { galleryIndex = index; lightboxImage.src = galleryImages[galleryIndex]; lightbox.classList.add('open'); lightbox.setAttribute('aria-hidden', 'false'); }; const changeLightbox = (direction) => { galleryIndex = (galleryIndex + direction + galleryImages.length) % galleryImages.length; lightboxImage.src = galleryImages[galleryIndex]; }; document.querySelectorAll('.gallery-item').forEach((item, index) => item.addEventListener('click', () => openLightbox(index))); lightbox.querySelector('.lightbox-close').addEventListener('click', () => lightbox.classList.remove('open')); lightbox.querySelector('.lightbox-prev').addEventListener('click', () => changeLightbox(-1)); lightbox.querySelector('.lightbox-next').addEventListener('click', () => changeLightbox(1));

const observeReveals = () => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), { threshold: 0.12 }); document.querySelectorAll('.reveal:not(.visible)').forEach((item) => observer.observe(item)); }; observeReveals();
window.addEventListener('keydown', (event) => { if (event.key === 'Escape') { setModal(false); lightbox.classList.remove('open'); } if (lightbox.classList.contains('open') && event.key === 'ArrowRight') changeLightbox(1); if (lightbox.classList.contains('open') && event.key === 'ArrowLeft') changeLightbox(-1); });
